"""PRJ0-85: Publish UML architecture diagrams from guide/ HTML to Confluence."""
from __future__ import annotations

import html as html_lib
import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# 7 diagrams to publish
UML_DIAGRAMS = [
    ("uml-system-context.html", "System Context Diagram"),
    ("uml-component.html", "Component Diagram"),
    ("uml-use-case.html", "Use Case Diagram"),
    ("uml-sequence-feature.html", "Sequence: Feature Dev Workflow"),
    ("uml-sequence-mcra.html", "Sequence: MCRA 4-Eye Approval"),
    ("uml-class-brain.html", "Class Diagram: Brain Model"),
    ("uml-deployment.html", "Deployment Diagram"),
]


def _base() -> str:
    return os.getenv("CONFLUENCE_BASE_URL", "").rstrip("/")


def _auth() -> tuple[str, str]:
    email = os.getenv("JIRA_USER_EMAIL", "")
    token = os.getenv("CONFLUENCE_API_TOKEN", "") or os.getenv("JIRA_API_TOKEN", "")
    return (email, token)


def _space_key() -> str:
    return os.getenv("CONFLUENCE_SPACE_KEY", "PZF")


def _configured() -> bool:
    base, (email, token) = _base(), _auth()
    return bool(base and email and token)


def _guide_dir() -> Path:
    """Locate the guide/ directory relative to this file or via env."""
    env_path = os.getenv("GUIDE_DIR")
    if env_path:
        return Path(env_path)
    # Walk up from services/ → backend/ → platform/ → repo root → guide/
    here = Path(__file__).resolve()
    for ancestor in here.parents:
        candidate = ancestor / "guide"
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError("guide/ directory not found")


def extract_mermaid(html_content: str) -> str:
    """Extract first Mermaid diagram source from HTML."""
    matches = re.findall(r'class="mermaid"[^>]*>(.*?)</div>', html_content, re.DOTALL)
    if not matches:
        return ""
    return html_lib.unescape(matches[0].strip())


def _build_page_body(title: str, mermaid_source: str, generated_at: str) -> str:
    escaped = (
        mermaid_source
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return (
        f"<h1>{title}</h1>\n"
        f"<p><em>Auto-published by PRJ0-85 at {generated_at}</em></p>\n"
        "<h2>Architecture Diagram</h2>\n"
        "<p>Copy the source below into a "
        '<a href="https://mermaid.js.org/intro/">Mermaid Live Editor</a> '
        "to view the rendered diagram.</p>\n"
        '<ac:structured-macro ac:name="code">\n'
        '  <ac:parameter ac:name="language">text</ac:parameter>\n'
        f"  <ac:plain-text-body>{escaped}</ac:plain-text-body>\n"
        "</ac:structured-macro>\n"
        f"<h2>Raw Source</h2>\n<pre>{escaped}</pre>"
    )


async def _find_page(client: httpx.AsyncClient, space_key: str, title: str) -> dict[str, Any] | None:
    resp = await client.get(
        f"{_base()}/rest/api/content",
        params={"spaceKey": space_key, "title": title, "expand": "version"},
    )
    if resp.status_code != 200:
        return None
    data = resp.json()
    results = data.get("results", [])
    return results[0] if results else None


async def _find_or_create_parent(client: httpx.AsyncClient, space_key: str) -> str | None:
    """Return page ID of 'Architecture' page, creating it if needed."""
    parent_title = os.getenv("CONFLUENCE_ARCH_PARENT_TITLE", "Architecture")
    existing = await _find_page(client, space_key, parent_title)
    if existing:
        return existing["id"]
    # Create the Architecture parent page
    payload = {
        "type": "page",
        "title": parent_title,
        "space": {"key": space_key},
        "body": {
            "storage": {
                "value": "<h1>Architecture</h1><p>UML Architecture Diagrams — auto-generated by PRJ0-85.</p>",
                "representation": "storage",
            }
        },
    }
    resp = await client.post(f"{_base()}/rest/api/content", json=payload)
    if resp.status_code in (200, 201):
        return resp.json()["id"]
    logger.error("Failed to create Architecture parent: %s", resp.text)
    return None


async def _upsert_page(
    client: httpx.AsyncClient,
    space_key: str,
    parent_id: str,
    title: str,
    body: str,
) -> dict[str, Any]:
    existing = await _find_page(client, space_key, title)
    if existing:
        page_id = existing["id"]
        version = existing["version"]["number"] + 1
        resp = await client.put(
            f"{_base()}/rest/api/content/{page_id}",
            json={
                "id": page_id,
                "type": "page",
                "title": title,
                "version": {"number": version},
                "ancestors": [{"id": parent_id}],
                "body": {"storage": {"value": body, "representation": "storage"}},
            },
        )
        return {"action": "updated", "page_id": page_id, "title": title, "status": resp.status_code}
    else:
        resp = await client.post(
            f"{_base()}/rest/api/content",
            json={
                "type": "page",
                "title": title,
                "space": {"key": space_key},
                "ancestors": [{"id": parent_id}],
                "body": {"storage": {"value": body, "representation": "storage"}},
            },
        )
        page_id = resp.json().get("id", "?") if resp.status_code in (200, 201) else "?"
        return {"action": "created", "page_id": page_id, "title": title, "status": resp.status_code}


async def publish_uml_diagrams() -> dict[str, Any]:
    """Publish all 7 UML diagrams to Confluence. Returns result summary."""
    if not _configured():
        return {"status": "skipped", "reason": "Confluence not configured", "results": []}

    guide_dir = _guide_dir()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    space_key = _space_key()

    results: list[dict[str, Any]] = []
    errors: list[str] = []

    async with httpx.AsyncClient(auth=_auth(), timeout=30.0) as client:
        parent_id = await _find_or_create_parent(client, space_key)
        if not parent_id:
            return {"status": "error", "reason": "Could not find/create Architecture parent page", "results": []}

        for filename, page_title in UML_DIAGRAMS:
            html_path = guide_dir / filename
            if not html_path.exists():
                errors.append(f"{filename}: file not found")
                results.append({"title": page_title, "status": "error", "reason": "file not found"})
                continue

            html_content = html_path.read_text(encoding="utf-8")
            mermaid_source = extract_mermaid(html_content)
            if not mermaid_source:
                errors.append(f"{filename}: no mermaid block found")
                results.append({"title": page_title, "status": "error", "reason": "no mermaid block"})
                continue

            body = _build_page_body(page_title, mermaid_source, generated_at)
            try:
                result = await _upsert_page(client, space_key, parent_id, page_title, body)
                results.append({**result, "file": filename})
                logger.info("Published '%s' → page %s (%s)", page_title, result.get("page_id"), result.get("action"))
            except Exception as exc:
                errors.append(f"{filename}: {exc}")
                results.append({"title": page_title, "status": "error", "reason": str(exc)})

    published = sum(1 for r in results if r.get("action") in ("created", "updated"))
    return {
        "status": "ok" if not errors else "partial",
        "published": published,
        "errors": errors,
        "results": results,
    }
